server:
    port: 8080
spring:
    application:
        name: example-redis
    redis:
        database: 15
        host: 192.168.1.3
        port: 6379
        password: Weijj0528!
        jedis:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1ms
                min-idle: 0

redisson:
    config:
        type: STANDALONE # 或者是CLUSTER, MASTER_SLAVE等，根据你的Redis部署类型来选择
        address: "${spring.redis.host}:${spring.redis.port}"
        password: "${spring.redis.password}" # 如果有密码的话
        # 更多配置可以根据需要添加，比如对于集群的配置
        # cluster:
        #   nodeAddresses: ["redis://127.0.0.1:7000", "redis://127.0.0.1:7001"]
