server:
    port: 8080
spring:
    application:
        name: example-swagger
swagger:
    enabled: true
    version: 1.0
    title: Swagger演示API
    description: API简介说明，本系统用于演示Swagger2功能
    contact-url: https://xxx.xxx.xxx
    contact-name: weijj0528
    contact-email: weijj0528@163.com
    base-package: com.github.weijj0528.example.swagger2