server:
    port: 8080
spring:
    application:
        name: ${rootArtifactId}
    # H2 控制台 其他数据源可移除
    h2:
        console:
            enabled: true
            path: /h2-console
    sql:
        init:
            platform: h2
    datasource:
        driver-class-name: org.h2.Driver
        type: com.zaxxer.hikari.HikariDataSource
        # 内存模式
        url: jdbc:h2:mem:test?MODE=MYSQL
        username: SA
        password:
    redis:
        database: 15
        host: 192.168.1.3
        port: 6379
        password: Weijj0528!

# Redisson
redisson:
    config:
        type: STANDALONE # 或者是CLUSTER, MASTER_SLAVE等，根据你的Redis部署类型来选择
        address: "${spring.redis.host}:${spring.redis.port}"
        password: "${spring.redis.password}" # 如果有密码的话
        # 更多配置可以根据需要添加，比如对于集群的配置
        # cluster:
        #   nodeAddresses: ["redis://127.0.0.1:7000", "redis://127.0.0.1:7001"]

# MyBatis
mybatis:
    mapper-locations:
        - classpath*:/mapper/*.xml

# Swagger
swagger:
    enabled: true
    version: 1.0
    title: Swagger演示API
    description: API简介说明，本系统用于演示Swagger2功能
    contact-url: https://xxx.xxx.xxx
    contact-name: 联系人
    contact-email: xxxxxx@163.com
    base-package: ${package}