server:
    port: 8080
spring:
    application:
        name: example-mybatis
    h2:
        console:
            enabled: true
    datasource:
        driver-class-name: org.h2.Driver
        type: com.zaxxer.hikari.HikariDataSource
        # 内存模式
        url: jdbc:h2:mem:test?MODE=MYSQL
        username: SA
        password:
        hikari:
            minimum-idle: 6
            maximum-pool-size: 20
            max-lifetime: 1800000
            idle-timeout: 600000
            connection-timeout: 30000
            connection-test-query: SELECT 1
    sql:
        init:
            platform: h2
    flyway:
        baseline-on-migrate: true
        fail-on-missing-locations: false
        locations: classpath:db/migration

mybatis:
    mapper-locations: classpath:mapper/*.xml
